version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "6001:6001"
    volumes:
      - .:/home/qstack
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - database
    ports:
      - "3001:3001"
    volumes:
      - .:/home/qstack
    environment:
      # print directly to terminal
      - PYTHONUNBUFFERED=1
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qstackdb
